name: optovka
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  scrollable_positioned_list: ^0.2.2
  async: ^2.8.2
  collection: ^1.15.0-nullsafety.4
  get_storage: ^2.0.3
  dartx: ^1.0.0
  equatable: ^2.0.3
  json_annotation: ^4.0.1
  json_serializable: ^4.1.4
  jwt_decoder: ^2.0.1
  dart_date: ^1.1.0
  flutter_dotenv: ^5.0.2
  dio: ^4.0.4
  uuid: ^3.0.4
  url_launcher: ^6.0.10
  mask_text_input_formatter: ^2.0.0
  modal_bottom_sheet: ^2.0.0
  auto_size_text: ^3.0.0-nullsafety.0
  google_fonts: ^2.1.0
  evil_icons_flutter: ^0.5.0
  font_awesome_flutter: ^9.1.0
  intl: ^0.17.0
  package_info: ^2.0.2
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.2
  get_cli: ^1.7.1
  sqflite: ^2.0.2
  cached_network_image: ^3.1.0
  path_provider: ^2.0.9
  get: 4.6.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.1.1
  dart_code_metrics: ^4.1.0
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

